/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/launch/builder/build.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/launch/builder/build.py:11: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
wandb: Currently logged in as: hyin66 (hyin66-university-of-wisconsin-madison). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.21.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.12
wandb: Run data is saved locally in /home/heqiy/trl_grpo/wandb/run-20250908_154929-8pkoau3t
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run grpo-final2-batch_std-easy-easy_batch_std
wandb: ‚≠êÔ∏è View project at https://wandb.ai/hyin66-university-of-wisconsin-madison/grpo-final2-difficulty
wandb: üöÄ View run at https://wandb.ai/hyin66-university-of-wisconsin-madison/grpo-final2-difficulty/runs/8pkoau3t
`torch_dtype` is deprecated! Use `dtype` instead!
INFO:accelerate.utils.modeling:Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 560343040 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
Arguments: Namespace(difficulty='easy', data_dir='data/gsm8k_difficulty_subsets', max_samples=None, format='qa', num_shots=2, model_name='Qwen/Qwen2.5-Math-1.5B', num_generations=8, learning_rate=1e-05, kl_beta=0.02, max_steps=1000, normalization='batch_std', use_wandb=True, wandb_project='grpo-final2-difficulty', wandb_run_name=None, exp_name='easy_batch_std')
Training on easy difficulty dataset
Loaded 4695 examples from easy difficulty dataset
Dataset loaded successfully with 4695 samples
Trainable parameters: 18464768
All parameters: 1562179072
Percentage trainable: 1.18%

Starting training:
  Difficulty: easy
  Normalization: batch_std
  Dataset size: 4695
  scale_rewards setting: batch
  0%|          | 0/1000 [00:00<?, ?it/s]/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
INFO:root:Batch accuracy: 4/8 = 50.0%
/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

üìä Current batch - Pass@8: 1.00, Accuracy: 50.00%
üìà Cumulative - Pass@8: 1.0000, Accuracy: 0.5000
   Total questions seen: 1
Traceback (most recent call last):
  File "/home/heqiy/trl_grpo/train_difficulty.py", line 318, in <module>
    main()
  File "/home/heqiy/trl_grpo/train_difficulty.py", line 301, in main
    trainer.train()
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/transformers/trainer.py", line 2328, in train
    return inner_training_loop(
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/transformers/trainer.py", line 2672, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/transformers/trainer.py", line 4009, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/trl/extras/profiling.py", line 98, in wrapper
    return func(self, *args, **kwargs)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/trl/trainer/grpo_trainer.py", line 1539, in compute_loss
    return self._compute_loss(model, inputs)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/trl/trainer/grpo_trainer.py", line 1550, in _compute_loss
    per_token_logps, entropies = self._get_per_token_logps_and_entropies(
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/trl/extras/profiling.py", line 98, in wrapper
    return func(self, *args, **kwargs)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/trl/trainer/grpo_trainer.py", line 828, in _get_per_token_logps_and_entropies
    entropies = entropy_from_logits(logits)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/trl/trainer/utils.py", line 1496, in entropy_from_logits
    chunk_entropy = -(torch.exp(logps) * logps).sum(-1)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 594.00 MiB. GPU 0 has a total capacity of 44.53 GiB of which 258.75 MiB is free. Process 3025290 has 6.99 GiB memory in use. Process 3025865 has 6.99 GiB memory in use. Process 3072973 has 4.42 GiB memory in use. Process 929893 has 20.59 GiB memory in use. Process 1058950 has 1.96 GiB memory in use. Process 1059569 has 1.65 GiB memory in use. Including non-PyTorch memory, this process has 1.65 GiB memory in use. Of the allocated memory 1.16 GiB is allocated by PyTorch, and 6.82 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: - 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: \ 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: | 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: / 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: - 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: 
wandb: Run history:
wandb:                 profiling/Time taken: DifficultyGRPOTrainer._calculate_rewards ‚ñÅ
wandb: profiling/Time taken: DifficultyGRPOTrainer._get_per_token_logps_and_entropies ‚ñà‚ñÅ
wandb:                    profiling/Time taken: DifficultyGRPOTrainer._prepare_inputs ‚ñà‚ñÅ
wandb:                       profiling/Time taken: DifficultyGRPOTrainer.compute_loss ‚ñÅ
wandb:         profiling/Time taken: DifficultyGRPOTrainer.correctness_reward_func_qa ‚ñÅ
wandb:              profiling/Time taken: DifficultyGRPOTrainer.format_reward_func_qa ‚ñÅ
wandb:              profiling/Time taken: DifficultyGRPOTrainer.transformers.generate ‚ñÅ
wandb:                                                           train/batch_accuracy ‚ñÅ
wandb:                                                      train/cumulative_accuracy ‚ñÅ
wandb:                                                     train/cumulative_pass_at_k ‚ñÅ
wandb:                                                                train/pass_at_k ‚ñÅ
wandb:                                                           train/questions_seen ‚ñÅ
wandb: 
wandb: Run summary:
wandb:                 profiling/Time taken: DifficultyGRPOTrainer._calculate_rewards 0.00808
wandb: profiling/Time taken: DifficultyGRPOTrainer._get_per_token_logps_and_entropies 0.15323
wandb:                    profiling/Time taken: DifficultyGRPOTrainer._prepare_inputs 2e-05
wandb:                       profiling/Time taken: DifficultyGRPOTrainer.compute_loss 0.23671
wandb:         profiling/Time taken: DifficultyGRPOTrainer.correctness_reward_func_qa 0.00244
wandb:              profiling/Time taken: DifficultyGRPOTrainer.format_reward_func_qa 0.00219
wandb:              profiling/Time taken: DifficultyGRPOTrainer.transformers.generate 65.56615
wandb:                                                           train/batch_accuracy 0.5
wandb:                                                      train/cumulative_accuracy 0.5
wandb:                                                     train/cumulative_pass_at_k 1.0
wandb:                                                                train/pass_at_k 1.0
wandb:                                                           train/questions_seen 1
wandb: 
wandb: üöÄ View run grpo-final2-batch_std-easy-easy_batch_std at: https://wandb.ai/hyin66-university-of-wisconsin-madison/grpo-final2-difficulty/runs/8pkoau3t
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20250908_154929-8pkoau3t/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread IntMsgThr:
Traceback (most recent call last):
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
        self.run()self.run()

  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/threading.py", line 953, in run
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 299, in check_internal_messages
    self._loop_check_status(
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 223, in _loop_check_status
    self._target(*self._args, **self._kwargs)
    local_handle = request()
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 267, in check_network_status
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 743, in deliver_internal_messages
    self._loop_check_status(
    return self._deliver_internal_messages(internal_message)  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 223, in _loop_check_status

    local_handle = request()
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 481, in _deliver_internal_messages
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 735, in deliver_network_status
    return self._deliver_record(record)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 428, in _deliver_record
    return self._deliver_network_status(status)
    handle = mailbox._deliver_record(record, interface=self)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in _deliver_network_status
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    return self._deliver_record(record)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 428, in _deliver_record
    interface._publish(record)
    handle = mailbox._deliver_record(record, interface=self)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    self._sock_client.send_record_publish(record)
    interface._publish(record)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self.send_server_request(server_req)
    self._sock_client.send_record_publish(record)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self._send_message(msg)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    self.send_server_request(server_req)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
    self._send_message(msg)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/heqiy/miniconda3/envs/verl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
